Bump to 0.7.2
mobilityhouse/ocpp pull request #138
Opened 2020-10-17 09:31 UTC by OrangeTux

2020-10-17 20:05 UTC, tropxy requested changes

2020-10-17 20:05 UTC, tropxy commented on CHANGELOG.md
> +* [#131](https://github.com/mobilityhouse/ocpp/issues/131) Ad CI support for Python 3.9. Thanks [@laysauchoa]](https://github.com/laysauchoa)!
Ad -> Add

2020-10-18 08:55 UTC, laysauchoa reviewed
so nice that you put a thankful note :dizzy:

2020-10-19 10:23 UTC, laysauchoa approved these changes
looks good!

2020-10-19 10:51 UTC, merged