Updated Readme to include support to OCPP 2.0.1
mobilityhouse/ocpp pull request #144
Opened 2020-10-22 21:18 UTC by tropxy

Enhanced the example by checking the subprotocols supported by the CS

2020-10-22 21:19 UTC, laysauchoa commented on README.rst
> +    def on_boot_notitication(self, charging_station, reason, **kwargs):
missing the 4 spaces ;)

2020-10-22 21:25 UTC, tropxy commented on README.rst
> +    def on_boot_notitication(self, charging_station, reason, **kwargs):
Damn you fast Laysa haha

2020-10-25 08:45 UTC, OrangeTux requested changes
Can you also update the `License` section and mention that  OCPP 2.0.1 are not MIT licensed?

2020-10-25 08:45 UTC, OrangeTux commented on README.rst
> +        requested_protocols = websocket.request_headers['Sec-WebSocket-Protocol']
The bounds of `websocket.request_headers` are not checked. This code will break with a `KeyError` if a client doesn't send the 'Sec-WebSocket-Protocol' header.

2020-10-26 12:30 UTC, OrangeTux requested changes
This comment hasn't been resolved yet:

> Can you also update the License section and mention that OCPP 2.0.1 are not MIT licensed?

2020-10-27 07:27 UTC, OrangeTux approved these changes

2020-10-27 07:36 UTC, merged