fix/typo: on_boot_notification
mobilityhouse/ocpp pull request #162
Opened 2020-12-06 13:26 UTC by laysauchoa

2020-12-06 14:50 UTC, tropxy approved these changes

2020-12-07 15:07 UTC, OrangeTux approved these changes

2020-12-07 15:09 UTC, OrangeTux requested changes
The same type appears more in the project. Can you fix all occurrences?

2020-12-07 15:14 UTC, laysauchoa commented
sure, done!

2020-12-07 15:24 UTC, OrangeTux approved these changes

2020-12-07 15:24 UTC, merged