Add v1.6 data types
mobilityhouse/ocpp pull request #250
Opened 2021-09-16 09:05 UTC by proelke

2021-11-18 08:35 UTC, OrangeTux requested changes
I suggest to remove the `CiStringXXXType` and the `IdToken` All other classes model a type; a bag of attributes. The `CiStringXXXType` and `IdToken` are merely a string with some limits on their length. 

It also creates a non-friendly API. To read the value of the an `IdTagInfo`:

``` python
assert IdTagInfo.parent_id_tag.id_token.ci_string_20 == 'my-rfid'
```

Ideally, I want the API to be:

``` python
assert IdTagInfo.parent_id_tag == 'my-rfid'
```

I'm not sure yet, a nice way to impose this length on attributes of type `CiStringXXXType` and `IdToken`. So for now I suggest that the length is not validated and replace the type hints of attributes using those types with `str`. What do yo think?

2021-11-18 08:35 UTC, OrangeTux commented on ocpp/v16/datatypes.py
> +    id_tag_info: IdTagInfo
This field is optional.

2021-11-18 08:35 UTC, OrangeTux commented on ocpp/v16/datatypes.py
> +    status: AvailabilityStatus
This type is AuthorizationStatus

2021-11-19 11:30 UTC, proelke commented
I was debating adding them from the beginning. Then I debated adding some kind of custom validator, but I figured you might be against the complexity for such a small thing. To avoid a dependency I could use a __post_init__ to verify the length of the string in IdTagInfo and remove the CiStringXXXType. Or I can just drop it all together and leave it as is.

2021-11-19 11:38 UTC, proelke commented on ocpp/v16/datatypes.py
> +    id_tag_info: IdTagInfo
Fixed.

2021-11-19 11:38 UTC, proelke commented on ocpp/v16/datatypes.py
> +    status: AvailabilityStatus
Fixed.

2021-11-19 12:09 UTC, OrangeTux commented
> To avoid a dependency I could use a post_init to verify the length of the string in IdTagInfo and remove the CiStringXXXType

I like that solution

2021-11-22 08:14 UTC, OrangeTux requested changes
The code looks good. Make sure to fix the lint errors so the CI job passes.

2021-11-22 12:19 UTC, proelke commented
@OrangeTux fixed up the linting issues

2021-11-25 10:56 UTC, merged