Add passwordString datatype enum
mobilityhouse/ocpp pull request #331
Opened 2022-04-21 08:24 UTC by mdwcrft

Adding a new datatype from the errata:

<img width="806" alt="Screenshot 2022-04-20 at 21 22 56" src="https://user-images.githubusercontent.com/34003459/164316390-3ffbf4f3-6057-4b26-a75f-ff8df235773b.png">

2022-05-11 15:08 UTC, proelke commented
This is still part of 2.0.1 but related to Errata that came out on 2021-10-01. See the attached doc.
[ocpp-2.0.1_part2_errata_v1_0.pdf](https://github.com/mobilityhouse/ocpp/files/8671107/ocpp-2.0.1_part2_errata_v1_0.pdf)
.

2022-10-31 09:14 UTC, tropxy submitted a review, later dismissed

2022-10-31 12:23 UTC, tropxy requested changes
can you add a test for this DataType Enum?
https://github.com/mobilityhouse/ocpp/blob/master/tests/v201/test_v201_enums.py

2022-10-31 13:12 UTC, tropxy approved these changes

2022-10-31 14:04 UTC, tropxy approved these changes

2022-10-31 14:09 UTC, merged