Add new connector types from errata
mobilityhouse/ocpp pull request #332
Opened 2022-04-21 08:26 UTC by mdwcrft

Adding 3 new connector types from the Errata, and any missing descriptions.

<img width="828" alt="Screenshot 2022-04-20 at 21 21 29" src="https://user-images.githubusercontent.com/34003459/164316130-46f3c6b8-4dd2-4c69-b8a9-39b2bb3ba8ab.png">

2022-05-11 15:44 UTC, mdwcrft commented
See https://github.com/mobilityhouse/ocpp/pull/331#issuecomment-1123906583

2022-10-31 09:20 UTC, tropxy requested changes

2022-10-31 09:20 UTC, tropxy commented on ocpp/v201/enums.py
> +    # IEC62196-2 Type 2 socket a.k.a. Scame
Type 3 and not type 2

2022-10-31 09:46 UTC, tropxy requested changes

2022-10-31 12:13 UTC, mdwcrft commented on ocpp/v201/enums.py
> +    # IEC62196-2 Type 2 socket a.k.a. Scame
Typo from spec, fixed here

2022-10-31 12:13 UTC, mdwcrft commented on ocpp/v201/enums.py
> +    # IEC62196-2 Type 2 socket a.k.a. Mennekes connector
Typo from spec, fixed here

2022-10-31 12:25 UTC, tropxy requested changes
could you also add a test for the ConnectorType enum?

https://github.com/mobilityhouse/ocpp/blob/master/tests/v201/test_v201_enums.py

2022-10-31 13:12 UTC, tropxy approved these changes

2022-10-31 13:44 UTC, merged