The serialisation of soc to SoC should not occur in camel case if it is existing at the beginning of a field
mobilityhouse/ocpp pull request #527
Opened 2023-11-13 13:13 UTC by Jared-Newell-Mobility

2023-11-15 07:14 UTC, OrangeTux reviewed
Do you've an example of an input that which casing is changed incorrectly?

2023-11-15 07:23 UTC, Jared-Newell-Mobility commented
Just checking there is an example here - https://github.com/mobilityhouse/ocpp/issues/523 ?

2023-11-15 07:33 UTC, OrangeTux requested changes
Can you update the [tests](https://github.com/mobilityhouse/ocpp/blob/c6129db91d00d721b51cca170a4a8f38225c9d85/tests/test_charge_point.py#L63-L72) to cover this change?

2024-02-13 14:48 UTC, OrangeTux approved these changes

2024-02-14 12:59 UTC, merged