bump to 2.0.0
mobilityhouse/ocpp pull request #692
Opened 2024-12-09 09:35 UTC by mdwcrft

2024-12-09 10:12 UTC, jerome-benoit commented
It's way too early to release 2.0.0 given the PRs backlog: 

+ OCPP 2 enums namespace fix
+ OCPP 2 type definition 
+ ...

2024-12-09 10:33 UTC, mdwcrft commented
> It's way too early to release 2.0.0 given the PRs backlog: 
> 
> 
> 
> + OCPP 2 enums namespace fix
> 
> + OCPP 2 type definitions 
> 
> + Version support documentation
> 
> + ...  

Happy to make another release this week with those changes once merged. The aim of 2.0.0 is to officially release all changes since the last official release 0.26 which was 11 months ago

2024-12-09 10:49 UTC, jainmohit2001 approved these changes

2024-12-09 10:51 UTC, jerome-benoit commented
> > It's way too early to release 2.0.0 given the PRs backlog:
> > 
> > * OCPP 2 enums namespace fix
> > * OCPP 2 type definitions
> > * Version support documentation
> > * ...
> 
> Happy to make another release this week with those changes once merged. The aim of 2.0.0 is to officially release all changes since the last official release 0.26 which was 11 months ago

The last official release is 1.0.0 and was not synced with GitHub release. 

A major is expected to include every single deprecation change *BEFORE*, not after.

2024-12-09 14:52 UTC, ajmirsky requested changes
please include pending PRs before releasing new library. 

And I agree with @jerome-benoit , since most people install via pypi, the last official release is 1.0.0, even if it wasn't marked in github as a release.

if anything, this chore should be to create a github release to match what was released to pypi as 1.0.0

2024-12-09 15:12 UTC, jainmohit2001 commented
Will merge the pending PR's before releasing 2.0.0

2024-12-09 15:26 UTC, ajmirsky commented
> Will merge the pending PR's before releasing 2.0.0

thanks! greatly appreciated!

2025-01-01 12:54 UTC, ajmirsky commented
@mdwcrft  @proelke @jerome-benoit once #699 is merged, any other things needed before a release? happy to help!

2025-01-01 15:02 UTC, jainmohit2001 commented
I don't see any changes coming as of now. We'll do a pre-release first and test things out e2e using our internal systems. We can go for a major release afterwards.

2025-01-01 15:06 UTC, jainmohit2001 commented
@mdwcrft Feel free to create another rc release. I'll try to expedite the testing process from my end.

2025-01-02 14:46 UTC, jainmohit2001 commented
Looking good.
I was able to migrate from OCPP 0.26.0 to OCPP 2.0.0rc4.
The migration was pretty easy, the IDE instantly picked up missing deprecated classes and enums. Bulk renaming for call, call results and enums helped me complete the migration in a few minutes.
Tested a successful charging flow on both OCPP 1.6 and OCPP 2.0.1 protocol.
@mdwcrft we can go with a major release.

2025-01-03 06:32 UTC, jainmohit2001 approved these changes

2025-01-03 06:33 UTC, merged